### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by tyamaguchi-ucla** [uclahs-cds/public-R-BoutrosLab-plotting-general#43]

**Comment by stefaneng** [comment]
Any progress on this?

**Comment by forbiddenpersimmon** [comment]
> Any progress on this?

Very basic README is done. I took the description from reference manual, let me know if this is not unacceptable. Would appreciate any suggestions on what to add i.e. specs, example plots

Also how many authors should I be including?

**Comment by tyamaguchi-ucla** [comment]
@forbiddenpersimmon Can you make a PR and we can make suggestions there?

**Comment by madisonjordan** [comment]
> Very basic README is done. I took the description from reference manual, let me know if this is not unacceptable. Would appreciate any suggestions on what to add i.e. specs, example plots

_Mentioning this since I don't see a branch on here that might be your readme:_

You might want to open a PR after pushing your branch so people can see what they can give feedback on. In addition, you can review your own PR if you have specific questions/comments about certain lines. It's okay to open PRs for this type of feedback as described (although possibly somewhat hidden) on our [confluence page](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Git+and+GitHub+Guide#GitandGitHubGuide-Review-GitHubFlowandConcepts). 
> You can open a Pull Request at any point during the development process: when you have little or no code but want to share some screenshots or general ideas, when you're stuck and need help or advice, or when you're ready for someone to review your work.

The basic instructions for pushing your own branch to the remote (the one on GitHub) is the same as in the [GitHub training](https://confluence.mednet.ucla.edu/x/-4gfCQ). 

More about PRs for you as a requester on our Code Review Best Practices page [here](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Best+Practice+on+GitHub+-+Check+List), if you're unfamiliar. Including how we name our branches and making commit messages, etc.
