### ISSUE TITLE
Repeating functions leads to warning messages

### ISSUE THREAD

**Issue by wenyan1996** [uclahs-cds/public-R-BoutrosLab-plotting-general#7]
Discussed with @bugh1 since there are some warning messages when library(BoutrosLab.plotting.survival),

Warning messages:
1: replacing previous import ‘BoutrosLab.plotting.general::get.correlation.p.and.corr’ by ‘BoutrosLab.statistics.general::get.correlation.p.and.corr’ when loading ‘BoutrosLab.plotting.survival’ 
2: replacing previous import ‘BoutrosLab.plotting.general::create.qqplot.fit.confidence.interval’ by ‘BoutrosLab.statistics.general::create.qqplot.fit.confidence.interval’ when loading ‘BoutrosLab.plotting.survival’ 
3: replacing previous import ‘BoutrosLab.plotting.general::ks.test.critical.value’ by ‘BoutrosLab.statistics.general::ks.test.critical.value’ when loading ‘BoutrosLab.plotting.survival’ 

Maybe because we have the same functions in the BoutrosLab.plotting.general and BoutrosLab.statistics.general?

**Comment by bugh1** [comment]
@dan-knight The historical context for this issue is that when we released BPG to CRAN last year, it had a couple of private Boutros Lab R package dependencies. In order for BPG to become a public package on CRAN, it cannot have private dependencies, so those functions were directly copied into BPG. The warning messages now appear when we have a package which imports both BPG and some other BL package, but they have the same function names (and in this case the same functions) so one is replaced by the other.

See this commit for which functions were copied: https://github.com/uclahs-cds/public-R-BoutrosLab-plotting-general/commit/fc64b269896dd02cd91bc031276bba37b00b9d68

**Comment by dan-knight** [comment]
These functions seem to have been included in BLstatistics in their initial commit, but not updated since then (August 2014). These should probably just live in BPG, since that's on CRAN already.

**Comment by bugh1** [comment]
I see 2 paths forward:
1. Remove the duplicating functions in other packages
2. Make the other packages public on CRAN, and remove the functions in BPG.

Option 2 might be the 'right' way to do it, since they are statistics functions, and do not necessarily belong in a plotting package.

**Comment by dan-knight** [comment]
2 seems like a better long term fix. Does @pboutros want the statistics package to be public?

A short term fix could be to keep the conflicting functions in BPG for now, and remove the outdated versions from BLstatistics. This would resolve the conflict and stop people accidentally using the old versions from BLstats. We could then move the functions into the statistics package once it's ready to submit to CRAN.

**Comment by pboutros** [comment]
We've never really decided what to do with this.  There isn't a whole lot in BPS that merits being on CRAN, it's mostly convenience functions.  Needs some discussion, comfortable leaving these warning messages for now
